import type { AppData } from '@/storage/types'

export const SEED_DATA: AppData = {
  settings: {
    distanceUnit: 'meters',
    temperatureUnit: 'celsius',
    theme: 'light',
    language: 'en',
    storageBackend: 'local',
    golfCourseApiKey: '',
  },
  players: [
    {
      id: 'player-1',
      name: 'Daniel',
      handicapIndex: 12.4,
      gender: 'male',
      clubs: [
        { id: 'club-1', type: 'Driver', brand: 'TaylorMade', carryDistance: 220 },
        { id: 'club-2', type: '3-Wood', brand: 'TaylorMade', carryDistance: 195 },
        { id: 'club-3', type: '5-Wood', brand: 'Callaway', carryDistance: 180 },
        { id: 'club-4', type: '4-Hybrid', brand: 'Titleist', carryDistance: 170 },
        { id: 'club-5', type: '5-Iron', brand: 'Titleist', carryDistance: 160 },
        { id: 'club-6', type: '6-Iron', brand: 'Titleist', carryDistance: 150 },
        { id: 'club-7', type: '7-Iron', brand: 'Titleist', carryDistance: 140 },
        { id: 'club-8', type: '8-Iron', brand: 'Titleist', carryDistance: 130 },
        { id: 'club-9', type: '9-Iron', brand: 'Titleist', carryDistance: 120 },
        { id: 'club-10', type: 'PW', brand: 'Titleist', carryDistance: 108 },
        { id: 'club-11', type: 'GW', brand: 'Vokey', carryDistance: 95 },
        { id: 'club-12', type: 'SW', brand: 'Vokey', carryDistance: 80 },
        { id: 'club-13', type: 'LW', brand: 'Vokey', carryDistance: 60 },
        { id: 'club-14', type: 'Putter', brand: 'Odyssey', carryDistance: 0 },
      ],
    },
    {
      id: 'player-2',
      name: 'Sofia',
      handicapIndex: 18.6,
      gender: 'female',
      clubs: [
        { id: 'club-20', type: 'Driver', brand: 'Callaway', carryDistance: 175 },
        { id: 'club-21', type: '5-Wood', brand: 'Callaway', carryDistance: 145 },
        { id: 'club-22', type: '7-Iron', brand: 'Ping', carryDistance: 115 },
        { id: 'club-23', type: '9-Iron', brand: 'Ping', carryDistance: 95 },
        { id: 'club-24', type: 'PW', brand: 'Ping', carryDistance: 82 },
        { id: 'club-25', type: 'SW', brand: 'Ping', carryDistance: 60 },
        { id: 'club-26', type: 'Putter', brand: 'Odyssey', carryDistance: 0 },
      ],
    },
    {
      id: 'player-3',
      name: 'Marco',
      handicapIndex: 24.0,
      gender: 'male',
      clubs: [],
    },
  ],
  courses: [
    {
      id: 'course-1',
      name: 'Riverside Golf Course',
      clubName: 'Riverside Country Club',
      tees: [
        { id: 'tee-1a', name: 'White', courseRating: 71.2, slopeRating: 128, totalDistance: 5840 },
        { id: 'tee-1b', name: 'Yellow', courseRating: 69.5, slopeRating: 122, totalDistance: 5480 },
        { id: 'tee-1c', name: 'Red', courseRating: 72.1, slopeRating: 126, totalDistance: 4920 },
      ],
      holes: [
        {
          number: 1,
          parByTee: { 'tee-1a': 4, 'tee-1b': 4, 'tee-1c': 4 },
          handicap: 7,
          distanceByTee: { 'tee-1a': 365, 'tee-1b': 340, 'tee-1c': 295 },
        },
        {
          number: 2,
          parByTee: { 'tee-1a': 3, 'tee-1b': 3, 'tee-1c': 3 },
          handicap: 15,
          distanceByTee: { 'tee-1a': 155, 'tee-1b': 140, 'tee-1c': 118 },
        },
        {
          number: 3,
          parByTee: { 'tee-1a': 5, 'tee-1b': 5, 'tee-1c': 5 },
          handicap: 3,
          distanceByTee: { 'tee-1a': 485, 'tee-1b': 460, 'tee-1c': 410 },
        },
        {
          number: 4,
          parByTee: { 'tee-1a': 4, 'tee-1b': 4, 'tee-1c': 4 },
          handicap: 1,
          distanceByTee: { 'tee-1a': 390, 'tee-1b': 365, 'tee-1c': 320 },
        },
        {
          number: 5,
          parByTee: { 'tee-1a': 4, 'tee-1b': 4, 'tee-1c': 4 },
          handicap: 11,
          distanceByTee: { 'tee-1a': 340, 'tee-1b': 320, 'tee-1c': 280 },
        },
        {
          number: 6,
          parByTee: { 'tee-1a': 3, 'tee-1b': 3, 'tee-1c': 3 },
          handicap: 17,
          distanceByTee: { 'tee-1a': 165, 'tee-1b': 148, 'tee-1c': 125 },
        },
        {
          number: 7,
          parByTee: { 'tee-1a': 4, 'tee-1b': 4, 'tee-1c': 4 },
          handicap: 5,
          distanceByTee: { 'tee-1a': 375, 'tee-1b': 352, 'tee-1c': 308 },
        },
        {
          number: 8,
          parByTee: { 'tee-1a': 5, 'tee-1b': 5, 'tee-1c': 5 },
          handicap: 9,
          distanceByTee: { 'tee-1a': 470, 'tee-1b': 445, 'tee-1c': 400 },
        },
        {
          number: 9,
          parByTee: { 'tee-1a': 4, 'tee-1b': 4, 'tee-1c': 4 },
          handicap: 13,
          distanceByTee: { 'tee-1a': 350, 'tee-1b': 330, 'tee-1c': 290 },
        },
        {
          number: 10,
          parByTee: { 'tee-1a': 4, 'tee-1b': 4, 'tee-1c': 4 },
          handicap: 2,
          distanceByTee: { 'tee-1a': 395, 'tee-1b': 370, 'tee-1c': 325 },
        },
        {
          number: 11,
          parByTee: { 'tee-1a': 3, 'tee-1b': 3, 'tee-1c': 3 },
          handicap: 16,
          distanceByTee: { 'tee-1a': 170, 'tee-1b': 150, 'tee-1c': 130 },
        },
        {
          number: 12,
          parByTee: { 'tee-1a': 5, 'tee-1b': 5, 'tee-1c': 5 },
          handicap: 4,
          distanceByTee: { 'tee-1a': 495, 'tee-1b': 470, 'tee-1c': 420 },
        },
        {
          number: 13,
          parByTee: { 'tee-1a': 4, 'tee-1b': 4, 'tee-1c': 4 },
          handicap: 8,
          distanceByTee: { 'tee-1a': 360, 'tee-1b': 338, 'tee-1c': 298 },
        },
        {
          number: 14,
          parByTee: { 'tee-1a': 4, 'tee-1b': 4, 'tee-1c': 4 },
          handicap: 10,
          distanceByTee: { 'tee-1a': 345, 'tee-1b': 325, 'tee-1c': 285 },
        },
        {
          number: 15,
          parByTee: { 'tee-1a': 3, 'tee-1b': 3, 'tee-1c': 3 },
          handicap: 18,
          distanceByTee: { 'tee-1a': 148, 'tee-1b': 132, 'tee-1c': 112 },
        },
        {
          number: 16,
          parByTee: { 'tee-1a': 4, 'tee-1b': 4, 'tee-1c': 4 },
          handicap: 6,
          distanceByTee: { 'tee-1a': 380, 'tee-1b': 355, 'tee-1c': 310 },
        },
        {
          number: 17,
          parByTee: { 'tee-1a': 5, 'tee-1b': 5, 'tee-1c': 5 },
          handicap: 12,
          distanceByTee: { 'tee-1a': 465, 'tee-1b': 440, 'tee-1c': 395 },
        },
        {
          number: 18,
          parByTee: { 'tee-1a': 4, 'tee-1b': 4, 'tee-1c': 4 },
          handicap: 14,
          distanceByTee: { 'tee-1a': 337, 'tee-1b': 320, 'tee-1c': 278 },
        },
      ],
    },
    {
      id: 'course-2',
      name: 'Hilltop 9',
      tees: [
        { id: 'tee-2a', name: 'Yellow', courseRating: 35.2, slopeRating: 118, totalDistance: 2720 },
      ],
      holes: [
        { number: 1, parByTee: { 'tee-2a': 4 }, handicap: 3, distanceByTee: { 'tee-2a': 340 } },
        { number: 2, parByTee: { 'tee-2a': 3 }, handicap: 7, distanceByTee: { 'tee-2a': 145 } },
        { number: 3, parByTee: { 'tee-2a': 5 }, handicap: 1, distanceByTee: { 'tee-2a': 450 } },
        { number: 4, parByTee: { 'tee-2a': 4 }, handicap: 5, distanceByTee: { 'tee-2a': 320 } },
        { number: 5, parByTee: { 'tee-2a': 3 }, handicap: 9, distanceByTee: { 'tee-2a': 135 } },
        { number: 6, parByTee: { 'tee-2a': 4 }, handicap: 2, distanceByTee: { 'tee-2a': 355 } },
        { number: 7, parByTee: { 'tee-2a': 4 }, handicap: 4, distanceByTee: { 'tee-2a': 330 } },
        { number: 8, parByTee: { 'tee-2a': 3 }, handicap: 8, distanceByTee: { 'tee-2a': 155 } },
        { number: 9, parByTee: { 'tee-2a': 5 }, handicap: 6, distanceByTee: { 'tee-2a': 490 } },
      ],
    },
  ],
  rounds: [
    {
      id: 'round-1',
      courseId: 'course-1',
      date: '2026-03-01T10:00:00.000Z',
      scoringSystem: 'stroke',
      playerRounds: [
        {
          playerId: 'player-1',
          teeId: 'tee-1a',
          totalGross: 86,
          totalNet: 72,
          holeScores: [
            {
              holeNumber: 1,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            { holeNumber: 2, grossScore: 3, netScore: 3, putts: 2, greenInRegulation: true },
            {
              holeNumber: 3,
              grossScore: 6,
              netScore: 5,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            {
              holeNumber: 4,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            {
              holeNumber: 5,
              grossScore: 4,
              netScore: 3,
              putts: 1,
              fairwayHit: true,
              greenInRegulation: true,
            },
            { holeNumber: 6, grossScore: 4, netScore: 4, putts: 2, greenInRegulation: false },
            {
              holeNumber: 7,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            {
              holeNumber: 8,
              grossScore: 6,
              netScore: 5,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            {
              holeNumber: 9,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            {
              holeNumber: 10,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            { holeNumber: 11, grossScore: 3, netScore: 3, putts: 1, greenInRegulation: true },
            {
              holeNumber: 12,
              grossScore: 6,
              netScore: 5,
              putts: 3,
              fairwayHit: true,
              greenInRegulation: false,
            },
            {
              holeNumber: 13,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            {
              holeNumber: 14,
              grossScore: 4,
              netScore: 3,
              putts: 1,
              fairwayHit: true,
              greenInRegulation: true,
            },
            { holeNumber: 15, grossScore: 3, netScore: 3, putts: 2, greenInRegulation: true },
            {
              holeNumber: 16,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            {
              holeNumber: 17,
              grossScore: 6,
              netScore: 5,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            {
              holeNumber: 18,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
          ],
        },
      ],
    },
    {
      id: 'round-2',
      courseId: 'course-1',
      date: '2026-03-08T09:30:00.000Z',
      scoringSystem: 'stroke',
      playerRounds: [
        {
          playerId: 'player-1',
          teeId: 'tee-1a',
          totalGross: 82,
          totalNet: 68,
          holeScores: [
            {
              holeNumber: 1,
              grossScore: 4,
              netScore: 3,
              putts: 1,
              fairwayHit: true,
              greenInRegulation: true,
            },
            { holeNumber: 2, grossScore: 3, netScore: 3, putts: 2, greenInRegulation: true },
            {
              holeNumber: 3,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: true,
            },
            {
              holeNumber: 4,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            {
              holeNumber: 5,
              grossScore: 4,
              netScore: 3,
              putts: 1,
              fairwayHit: true,
              greenInRegulation: true,
            },
            { holeNumber: 6, grossScore: 3, netScore: 3, putts: 1, greenInRegulation: true },
            {
              holeNumber: 7,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            {
              holeNumber: 8,
              grossScore: 5,
              netScore: 4,
              putts: 1,
              fairwayHit: true,
              greenInRegulation: true,
            },
            {
              holeNumber: 9,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            {
              holeNumber: 10,
              grossScore: 4,
              netScore: 3,
              putts: 1,
              fairwayHit: true,
              greenInRegulation: true,
            },
            { holeNumber: 11, grossScore: 4, netScore: 4, putts: 2, greenInRegulation: false },
            {
              holeNumber: 12,
              grossScore: 6,
              netScore: 5,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            {
              holeNumber: 13,
              grossScore: 4,
              netScore: 3,
              putts: 1,
              fairwayHit: true,
              greenInRegulation: true,
            },
            {
              holeNumber: 14,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            { holeNumber: 15, grossScore: 3, netScore: 3, putts: 2, greenInRegulation: true },
            {
              holeNumber: 16,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            {
              holeNumber: 17,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: true,
            },
            {
              holeNumber: 18,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
          ],
        },
        {
          playerId: 'player-2',
          teeId: 'tee-1c',
          totalGross: 98,
          totalNet: 78,
          holeScores: [
            {
              holeNumber: 1,
              grossScore: 6,
              netScore: 5,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            { holeNumber: 2, grossScore: 4, netScore: 3, putts: 2, greenInRegulation: false },
            {
              holeNumber: 3,
              grossScore: 7,
              netScore: 5,
              putts: 3,
              fairwayHit: false,
              greenInRegulation: false,
            },
            {
              holeNumber: 4,
              grossScore: 6,
              netScore: 4,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            {
              holeNumber: 5,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            { holeNumber: 6, grossScore: 4, netScore: 3, putts: 2, greenInRegulation: false },
            {
              holeNumber: 7,
              grossScore: 6,
              netScore: 4,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            {
              holeNumber: 8,
              grossScore: 6,
              netScore: 5,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            {
              holeNumber: 9,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            {
              holeNumber: 10,
              grossScore: 6,
              netScore: 5,
              putts: 3,
              fairwayHit: false,
              greenInRegulation: false,
            },
            { holeNumber: 11, grossScore: 4, netScore: 3, putts: 2, greenInRegulation: false },
            {
              holeNumber: 12,
              grossScore: 7,
              netScore: 5,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            {
              holeNumber: 13,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            {
              holeNumber: 14,
              grossScore: 5,
              netScore: 4,
              putts: 1,
              fairwayHit: true,
              greenInRegulation: true,
            },
            { holeNumber: 15, grossScore: 4, netScore: 4, putts: 2, greenInRegulation: false },
            {
              holeNumber: 16,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            {
              holeNumber: 17,
              grossScore: 7,
              netScore: 5,
              putts: 3,
              fairwayHit: false,
              greenInRegulation: false,
            },
            {
              holeNumber: 18,
              grossScore: 6,
              netScore: 5,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
          ],
        },
      ],
    },
    {
      id: 'round-3',
      courseId: 'course-2',
      date: '2026-03-12T14:00:00.000Z',
      scoringSystem: 'stroke',
      playerRounds: [
        {
          playerId: 'player-1',
          teeId: 'tee-2a',
          totalGross: 39,
          totalNet: 33,
          holeScores: [
            {
              holeNumber: 1,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            { holeNumber: 2, grossScore: 3, netScore: 3, putts: 1, greenInRegulation: true },
            {
              holeNumber: 3,
              grossScore: 6,
              netScore: 5,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            {
              holeNumber: 4,
              grossScore: 4,
              netScore: 3,
              putts: 1,
              fairwayHit: true,
              greenInRegulation: true,
            },
            { holeNumber: 5, grossScore: 3, netScore: 3, putts: 2, greenInRegulation: true },
            {
              holeNumber: 6,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            {
              holeNumber: 7,
              grossScore: 4,
              netScore: 3,
              putts: 1,
              fairwayHit: true,
              greenInRegulation: true,
            },
            { holeNumber: 8, grossScore: 4, netScore: 3, putts: 2, greenInRegulation: false },
            {
              holeNumber: 9,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
          ],
        },
        {
          playerId: 'player-3',
          teeId: 'tee-2a',
          totalGross: 48,
          totalNet: 36,
          holeScores: [
            {
              holeNumber: 1,
              grossScore: 6,
              netScore: 4,
              putts: 3,
              fairwayHit: false,
              greenInRegulation: false,
            },
            { holeNumber: 2, grossScore: 4, netScore: 3, putts: 2, greenInRegulation: false },
            {
              holeNumber: 3,
              grossScore: 7,
              netScore: 5,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            {
              holeNumber: 4,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            { holeNumber: 5, grossScore: 4, netScore: 3, putts: 2, greenInRegulation: false },
            {
              holeNumber: 6,
              grossScore: 6,
              netScore: 4,
              putts: 3,
              fairwayHit: false,
              greenInRegulation: false,
            },
            {
              holeNumber: 7,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            { holeNumber: 8, grossScore: 5, netScore: 4, putts: 2, greenInRegulation: false },
            {
              holeNumber: 9,
              grossScore: 6,
              netScore: 5,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
          ],
        },
      ],
    },
    // Round 4: Stableford round with varied point outcomes
    {
      id: 'round-4',
      courseId: 'course-1',
      date: '2026-03-14T11:00:00.000Z',
      scoringSystem: 'stableford',
      playerRounds: [
        {
          playerId: 'player-1',
          teeId: 'tee-1a',
          totalGross: 84,
          totalNet: 70,
          holeScores: [
            // Hole 1: par 4, hcp 7 — bogey (1 pt net)
            {
              holeNumber: 1,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            // Hole 2: par 3, hcp 15 — par (2 pts)
            { holeNumber: 2, grossScore: 3, netScore: 3, putts: 1, greenInRegulation: true },
            // Hole 3: par 5, hcp 3 — eagle! (4 pts net, chip-in 0 putts)
            {
              holeNumber: 3,
              grossScore: 3,
              netScore: 2,
              putts: 0,
              fairwayHit: true,
              greenInRegulation: false,
            },
            // Hole 4: par 4, hcp 1 — birdie (3 pts net)
            {
              holeNumber: 4,
              grossScore: 4,
              netScore: 3,
              putts: 1,
              fairwayHit: true,
              greenInRegulation: true,
            },
            // Hole 5: par 4, hcp 11 — double bogey (0 pts)
            {
              holeNumber: 5,
              grossScore: 6,
              netScore: 5,
              putts: 3,
              fairwayHit: false,
              greenInRegulation: false,
            },
            // Hole 6: par 3, hcp 17 — hole-in-one! (5 pts — albatross equivalent on par 3)
            { holeNumber: 6, grossScore: 1, netScore: 1, putts: 0, greenInRegulation: true },
            // Hole 7: par 4, hcp 5 — par (2 pts net)
            {
              holeNumber: 7,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            // Hole 8: par 5, hcp 9 — birdie (3 pts net)
            {
              holeNumber: 8,
              grossScore: 5,
              netScore: 4,
              putts: 1,
              fairwayHit: true,
              greenInRegulation: true,
            },
            // Hole 9: par 4, hcp 13 — triple bogey (0 pts)
            {
              holeNumber: 9,
              grossScore: 7,
              netScore: 6,
              putts: 3,
              fairwayHit: false,
              greenInRegulation: false,
            },
            // Hole 10: par 4, hcp 2 — par (2 pts net)
            {
              holeNumber: 10,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            // Hole 11: par 3, hcp 16 — birdie (3 pts)
            { holeNumber: 11, grossScore: 2, netScore: 2, putts: 1, greenInRegulation: true },
            // Hole 12: par 5, hcp 4 — par (2 pts net)
            {
              holeNumber: 12,
              grossScore: 6,
              netScore: 5,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            // Hole 13: par 4, hcp 8 — bogey (1 pt)
            {
              holeNumber: 13,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            // Hole 14: par 4, hcp 10 — par (2 pts net)
            {
              holeNumber: 14,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            // Hole 15: par 3, hcp 18 — bogey (1 pt)
            { holeNumber: 15, grossScore: 4, netScore: 4, putts: 2, greenInRegulation: false },
            // Hole 16: par 4, hcp 6 — double bogey (0 pts)
            {
              holeNumber: 16,
              grossScore: 7,
              netScore: 6,
              putts: 3,
              fairwayHit: false,
              greenInRegulation: false,
            },
            // Hole 17: par 5, hcp 12 — eagle (4 pts)
            {
              holeNumber: 17,
              grossScore: 3,
              netScore: 2,
              putts: 1,
              fairwayHit: true,
              greenInRegulation: true,
            },
            // Hole 18: par 4, hcp 14 — par (2 pts)
            {
              holeNumber: 18,
              grossScore: 4,
              netScore: 3,
              putts: 1,
              fairwayHit: true,
              greenInRegulation: true,
            },
          ],
        },
        {
          playerId: 'player-2',
          teeId: 'tee-1c',
          totalGross: 100,
          totalNet: 80,
          holeScores: [
            {
              holeNumber: 1,
              grossScore: 6,
              netScore: 5,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            { holeNumber: 2, grossScore: 4, netScore: 3, putts: 2, greenInRegulation: false },
            {
              holeNumber: 3,
              grossScore: 7,
              netScore: 5,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            {
              holeNumber: 4,
              grossScore: 5,
              netScore: 3,
              putts: 1,
              fairwayHit: true,
              greenInRegulation: true,
            },
            {
              holeNumber: 5,
              grossScore: 6,
              netScore: 5,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            { holeNumber: 6, grossScore: 5, netScore: 4, putts: 2, greenInRegulation: false },
            {
              holeNumber: 7,
              grossScore: 6,
              netScore: 4,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            {
              holeNumber: 8,
              grossScore: 6,
              netScore: 5,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            {
              holeNumber: 9,
              grossScore: 5,
              netScore: 4,
              putts: 1,
              fairwayHit: true,
              greenInRegulation: true,
            },
            {
              holeNumber: 10,
              grossScore: 6,
              netScore: 4,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            { holeNumber: 11, grossScore: 3, netScore: 3, putts: 1, greenInRegulation: true },
            {
              holeNumber: 12,
              grossScore: 7,
              netScore: 5,
              putts: 3,
              fairwayHit: false,
              greenInRegulation: false,
            },
            {
              holeNumber: 13,
              grossScore: 5,
              netScore: 4,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
            {
              holeNumber: 14,
              grossScore: 6,
              netScore: 5,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            { holeNumber: 15, grossScore: 4, netScore: 3, putts: 2, greenInRegulation: false },
            {
              holeNumber: 16,
              grossScore: 6,
              netScore: 5,
              putts: 2,
              fairwayHit: false,
              greenInRegulation: false,
            },
            {
              holeNumber: 17,
              grossScore: 7,
              netScore: 5,
              putts: 3,
              fairwayHit: true,
              greenInRegulation: false,
            },
            {
              holeNumber: 18,
              grossScore: 6,
              netScore: 5,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: false,
            },
          ],
        },
      ],
    },
    // Round 5: Stroke play with notable scores (eagle, hole-in-one, high scores)
    {
      id: 'round-5',
      courseId: 'course-2',
      date: '2026-03-15T08:00:00.000Z',
      scoringSystem: 'stroke',
      playerRounds: [
        {
          playerId: 'player-1',
          teeId: 'tee-2a',
          totalGross: 31,
          totalNet: 25,
          holeScores: [
            // Birdie
            {
              holeNumber: 1,
              grossScore: 3,
              netScore: 2,
              putts: 1,
              fairwayHit: true,
              greenInRegulation: true,
            },
            // Hole-in-one on par 3
            { holeNumber: 2, grossScore: 1, netScore: 1, putts: 0, greenInRegulation: true },
            // Albatross (double eagle) on par 5
            {
              holeNumber: 3,
              grossScore: 2,
              netScore: 1,
              putts: 1,
              fairwayHit: true,
              greenInRegulation: true,
            },
            // Par
            {
              holeNumber: 4,
              grossScore: 4,
              netScore: 3,
              putts: 2,
              fairwayHit: true,
              greenInRegulation: true,
            },
            // Bogey
            { holeNumber: 5, grossScore: 4, netScore: 4, putts: 2, greenInRegulation: false },
            // Double bogey
            {
              holeNumber: 6,
              grossScore: 6,
              netScore: 5,
              putts: 3,
              fairwayHit: false,
              greenInRegulation: false,
            },
            // Par with chip-in (0 putts)
            {
              holeNumber: 7,
              grossScore: 4,
              netScore: 3,
              putts: 0,
              fairwayHit: true,
              greenInRegulation: false,
            },
            // Triple bogey
            { holeNumber: 8, grossScore: 6, netScore: 5, putts: 2, greenInRegulation: false },
            // Condor — hole-in-one on par 5!
            {
              holeNumber: 9,
              grossScore: 1,
              netScore: 0,
              putts: 0,
              fairwayHit: true,
              greenInRegulation: true,
            },
          ],
        },
      ],
    },
  ],
  exportedAt: '2026-03-16T00:00:00.000Z',
}
